### PR TITLE
Make it build with ghc 9.10

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by AndreasPK** [comment]
If you fix the conflict I'm happy to merge this.

**Comment by erikd** [comment]
Conflict fixed. Hacakge update (even just a metadata edit) would be appreciated as well.

**Comment by AndreasPK** [comment]
I will wait for ci to pass just in case. Should I get distracted feel free to ping me once it's passed.

> Hacakge update (even just a metadata edit) would be appreciated as well.

I hope to update it similarly once CI is green for that.

**Comment by erikd** [comment]
CI still had not run when I looked at it this morning so I touched the top commit and force pushed hoping to get it picked up by the runner. Now its waiting for you to approve it.

**Comment by AndreasPK** [comment]
I think the free CI is just overloaded with many people updating things for 9.10 currently. CI hasn't run for my last commit on master yet either.

**Comment by erikd** [comment]
@AndreasPK According to my view this PR still has "1 workflow awaiting approval". I think there is a button somewhere for you to press (but I do not see it).

**Comment by AndreasPK** [comment]
> @AndreasPK According to my view this PR still has "1 workflow awaiting approval". I think there is a button somewhere for you to press (but I do not see it).

Yes, I had approved but I think it reset when you force pushed to your master branch. Re-approved and let's see if ci is faster now :D The run on master timed out since no runner was found in 24 hours ❌ But that shouldn't affect the MR

**Comment by AndreasPK** [comment]
But looking at other repos using haskell-ci i suspect I might have to update the config for the jobs to get picked up.

**Comment by AndreasPK** [comment]
Well your changes to me seem trivial and correct so I won't make the CI issue your problem.

**Comment by erikd** [comment]
Thanks. Would also greatly appreciate a Hackage metadata edit.

**Comment by AndreasPK** [comment]
[> Thanks. Would also greatly appreciate a Hackage metadata edit.

](https://hackage.haskell.org/package/dom-lt-0.2.3/revisions/)

**Pull request merged**
